[package]
name = "monkey"
version = "0.1.0"
authors = ["juliangautier"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jemallocator = "0.3.2"
indexmap = "1.3.2"